### ISSUE TITLE
The email id is not valid

### ISSUE THREAD

**Issue by khannavidur** [OpenGenus/ProjectBot#4]
Hi

I tried sending a mail to ohh@opengenus.com and got a failure. I wish to join the team if its still active.  Please suggest further course of action

**Comment by sbshah97** [comment]
Can an IRC Channel be created to facilitate communication between members?

**Comment by AdiChat** [comment]
Somehow, I overlooked this issue.

Anyways, communication issues have been resolved long back and invite has been send.
